export interface RenderOptions {
  serverImage: string;
  webImage: string;
  betterAuthSecret: string;
  domain: string;
  postgresPassword: string;
  acmeEmail: string;
}

export function renderPcEnv(opts: RenderOptions): string {
  return `# Generated by create-nyxel — PC mode.
# Reference: docker-compose.yml in this directory.

BETTER_AUTH_SECRET=${opts.betterAuthSecret}

# Optional — enables Anthropic cloud models in the model picker.
ANTHROPIC_API_KEY=
`;
}

export function renderServerEnv(opts: RenderOptions): string {
  return `# Generated by create-nyxel — Server mode.
# Reference: docker-compose.yml in this directory.

# The domain Caddy requests a TLS certificate for.
NYXEL_DOMAIN=${opts.domain}

# Email address used for ACME account registration / certificate management.
ACME_EMAIL=${opts.acmeEmail}

# Postgres password (also used inside DATABASE_URL).
POSTGRES_PASSWORD=${opts.postgresPassword}

# Used to sign Better-Auth session tokens.
BETTER_AUTH_SECRET=${opts.betterAuthSecret}

# Optional — enables Anthropic cloud models in the model picker.
ANTHROPIC_API_KEY=
`;
}

export function renderPcCompose(opts: RenderOptions): string {
  return `# Generated by create-nyxel — PC mode.
# Uses the published Nyxel images; no source checkout required.
# Usage: docker compose up -d

services:
  server:
    image: ${opts.serverImage}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NYXEL_MODE: pc
      DB_DRIVER: sqlite
      DATABASE_URL: /data/nyxel.sqlite
      BETTER_AUTH_SECRET: \${BETTER_AUTH_SECRET:?set BETTER_AUTH_SECRET in .env}
      BETTER_AUTH_URL: http://localhost:3001
      WEB_ORIGIN: http://localhost:3000
      PUBLIC_APP_URL: http://localhost:3000
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      LMSTUDIO_BASE_URL: http://host.docker.internal:1234
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
    volumes:
      - nyxel-data:/data
    ports:
      - "3001:3001"
    restart: unless-stopped

  web:
    image: ${opts.webImage}
    environment:
      NEXT_PUBLIC_SERVER_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  nyxel-data:
`;
}

export function renderServerCompose(opts: RenderOptions): string {
  return `# Generated by create-nyxel — Server mode.
# Uses the published Nyxel images; no source checkout required.
# Usage: docker compose up -d

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: nyxel
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: nyxel
    volumes:
      - nyxel-postgres:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    image: ${opts.serverImage}
    environment:
      NYXEL_MODE: server
      DB_DRIVER: pg
      DATABASE_URL: postgres://nyxel:\${POSTGRES_PASSWORD}@postgres:5432/nyxel
      BETTER_AUTH_SECRET: \${BETTER_AUTH_SECRET:?set BETTER_AUTH_SECRET in .env}
      BETTER_AUTH_URL: https://\${NYXEL_DOMAIN}
      WEB_ORIGIN: https://\${NYXEL_DOMAIN}
      PUBLIC_APP_URL: https://\${NYXEL_DOMAIN}
      NYXEL_DOMAIN: \${NYXEL_DOMAIN:?set NYXEL_DOMAIN in .env}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
    depends_on:
      - postgres
    restart: unless-stopped

  web:
    image: ${opts.webImage}
    environment:
      NEXT_PUBLIC_SERVER_URL: https://\${NYXEL_DOMAIN}
    depends_on:
      - server
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      NYXEL_DOMAIN: \${NYXEL_DOMAIN:?set NYXEL_DOMAIN in .env}
      ACME_EMAIL: \${ACME_EMAIL:-}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - nyxel-caddy-data:/data
      - nyxel-caddy-config:/config
    depends_on:
      - server
      - web
    restart: unless-stopped

volumes:
  nyxel-postgres:
  nyxel-caddy-data:
  nyxel-caddy-config:
`;
}

export const CADDYFILE = `{$NYXEL_DOMAIN:localhost} {
	encode zstd gzip

	header {
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
		X-Frame-Options SAMEORIGIN
	}

	@health path /healthz
	handle @health {
		respond "ok" 200
	}

	@api path /trpc/* /api/*
	handle @api {
		reverse_proxy server:3001
	}

	handle {
		reverse_proxy web:3000
	}
}
`;
